# Generated by Django 3.2.16 on 2024-11-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_published',
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
